apiVersion: batch/v1
kind: Job
metadata:
  name: sync1
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: >
         curl -H "Content-Type: application/json" -d '[{"labels":{"alertname":"TestAlert2”}}]’ alertmanager.192.168.99.100.nip.io/api/v1/alerts
      restartPolicy: Never
  backoffLimit: 0
