apiVersion: batch/v1
kind: Job
metadata:
  name: sync1
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["curl", "--data-binary", "@-", "http://alertmanager.192.168.99.100.nip.io/api/v1/alerts << EOS
[
  {
    "labels": {
      "alertname": "presto_down",
      "severity": "major"
    },
    "annotations": {
      "summary": "some presto node is down! now presto has ${presto_nodes} nodes.."
    }
  }
]
EOS"]
      restartPolicy: Never
  backoffLimit: 0
